version: '3.6'

services:
    webapi:
        container_name: webapp
        image: webapp
        build:
            context: .
            dockerfile: Fake images/Dockerfile
        ports:
            - 7171:8080

    mssql-server:
        image: mcr.microsoft.com/mssql/server
        environment:
          SA_PASSWORD: YourPassword123
          ACCEPT_EULA: Y
          MSSQL_PID: Express
        ports:
          - "1433:1433"

    redis:
        container_name: redis
        image: redis:latest
        ports:
          - "6379:6379"