version: '3.6'

services:
    mssql-server:
        image: mcr.microsoft.com/mssql/server
        environment:
          SA_PASSWORD: YourPassword123
          ACCEPT_EULA: Y
          MSSQL_PID: Express
        ports:
          - "1433:1433"

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.11-management
        ports:
            - "5672:5672"
            - "15672:15672"

    apigateway:
        container_name: apigateway
        image: apigateway
        build:
            context: .
            dockerfile: OcelotGateWay/Dockerfile
        ports:
            - 7171:8080    

    userapi:
        container_name: userapi
        image: userapi
        build:
            context: .
            dockerfile: UserApi/Dockerfile
        ports:
            - 7173:8080
        depends_on:
            - mssql-server

    uploadapi:
        container_name: uploadapi
        image: uploadapi
        build:
            context: .
            dockerfile: UploadApi/Dockerfile
        ports:
            - 7174:8080
        depends_on:
            - mssql-server

    resizeapi:
        container_name: resizeapi
        image: resizeapi
        build:
            context: .
            dockerfile: ResizeApi/Dockerfile
        ports:
            - 7175:8080
        depends_on:
            - mssql-server

    removebackapi:
        container_name: removebackapi
        image: removebackapi
        build:
            context: .
            dockerfile: RemoveBackApi/Dockerfile
        ports:
            - 7176:8080
        depends_on:
            - mssql-server

    overlayapi:
        container_name: overlayapi
        image: overlayapi
        build:
            context: .
            dockerfile: OverlayApi/Dockerfile
        ports:
            - 7177:8080
        depends_on:
            - mssql-server